import {BuildFeature, Steps, Contents} from "./editorial.mjs";
import {socialMetadata} from "./site-shell.mjs";
import {glassFilter} from "./glass-filter.mjs";
import {Button,Brand,Card,Badge,Section,Field,Disclosure,escapeHTML} from '../ui/components.mjs';
const example=(title,markup,code)=>`<article class="example ui-stack"><h3>${escapeHTML(title)}</h3><div class="demo ui-cluster">${markup}</div><pre tabindex="0"><code>${escapeHTML(code)}</code></pre></article>`;
export default function Catalog(){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Developer reference · Azivor component library</title>${socialMetadata({title:"Developer reference · Azivor component library",description:"Internal design tokens and UI demonstrations for Azivor developers. Demo fields do not submit or save data.",path:"/components/",noindex:true})}<meta name="description" content="Reusable components, design tokens, and examples for Azivor."><link rel="icon" type="image/png" href="/azivor-logo.png"><link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600&family=EB+Garamond:ital,wght@0,400;0,500;1,400&display=swap" rel="stylesheet"><link rel="stylesheet" href="/ui/tokens.css"><link rel="stylesheet" href="/ui/base.css"><link rel="stylesheet" href="/ui/components.css"><link rel="stylesheet" href="/content.css"><link rel="stylesheet" href="/catalog.css"><link rel="stylesheet" href="/category-cards.css"></head><body class="catalog">${glassFilter}<a class="skip-link" href="#main">Skip to content</a><header class="ui-container catalog-header">${Brand()}${Button({label:'View homepage',href:'/',variant:'ghost',size:'small'})}</header><main class="ui-container" id="main"><div class="catalog-intro ui-stack">${Badge({label:'Developer reference · UI library v1'})}<h1>Component library.</h1><p class="ui-body">Developer reference for the foundations and reusable pieces behind Azivor. These are UI demonstrations, not learner activities. Demo fields do not submit or save data.</p><nav class="catalog-nav ui-cluster" aria-label="Library sections"><a href="#foundations">Foundations</a><a href="#buttons">Buttons</a><a href="#surfaces">Surfaces</a><a href="#category-cards">Category cards</a><a href="#information-layout">Information layout</a><a href="#glass-nav">Scroll navigation</a><a href="#forms">Forms</a><a href="#patterns">Patterns</a><a href="#usage">Build a page</a></nav></div>
${Section({id:'foundations',title:'The foundations',children:`<div class="swatches ui-grid">${[['Sky','--color-sky'],['Cyan','--color-cyan'],['Ink','--color-ink'],['Accent','--color-accent'],['Reading','--information-white'],['Process','--information-blue'],['Support','--information-silver']].map(([name,token])=>`<div class="swatch"><div style="background:var(${token})"></div><strong>${name}</strong><code>${token}</code></div>`).join('')}</div><div class="ui-grid">${Card({variant:'solid',children:'<h3 class="ui-title">One serif moment.</h3><p class="ui-body">EB Garamond · homepage opening headline only</p>'})}${Card({variant:'solid',children:'<h3 class="ui-title">Geist everywhere else.</h3><p class="ui-body">Geist · all other headings, body text, and controls</p>'})}</div><p class="ui-body">Spacing: 4, 8, 12, 16, 24, 32, 48, 64px. Corners: 11px controls, 15px cards, 20px panels, 12px overlays, 6px compact overlays. Edit tokens once to update the shared system.</p>`})}
${Section({id:'buttons',title:'Actions, with a little light.',children:example('Primary',Button({label:'Explore',href:'#surfaces',icon:'down'}),"Button({ label: 'Explore', href: '#surfaces', icon: 'down' })")+example('Glass and outline',Button({label:'Glass',href:'#surfaces',variant:'glass'})+Button({label:'Outline',href:'#surfaces',variant:'ghost'}),"Button({ label: 'Glass', href: '#surfaces', variant: 'glass' })")+example('Sizes and disabled state',Button({label:'Small',href:'#usage',size:'small'})+Button({label:'Large',href:'#usage',size:'large'})+Button({label:'Unavailable',disabled:true}),"Button({ label: 'Unavailable', disabled: true })")+'<p class="ui-body">Use links for navigation and native buttons for actions. Hover or focus a primary action to see the light sweep. Motion is reduced automatically when requested by the device.</p>'})}
${Section({id:'surfaces',title:'Glass that keeps its depth.',children:`<div class="surface-stage ui-grid">${Card({variant:'light',children:'<h3 class="ui-title">Light glass</h3><p>For subtle layering over color.</p>'})}${Card({variant:'dark',children:'<h3 class="ui-title">Dark glass</h3><p class="ui-body">A translucent surface for focused content.</p>'})}${Card({variant:'solid',children:'<h3 class="ui-title">Solid surface</h3><p class="ui-body">For dense content and forms.</p>'})}${Card({variant:'silver',children:'<h3 class="ui-title">Silver panel</h3><p class="ui-body">A cool, opaque foundation for layered content.</p>'})}</div><pre tabindex="0"><code>${escapeHTML("Card({ variant: 'dark', children: '<h3>Your content</h3>' })")}</code></pre>`})}
${Section({id:'category-cards',title:'Category cards',children:`<div class="category-card-gallery">
  <a class="category-card category-card--feature" href="/explore/#build"><span class="category-card-copy"><h3>Build</h3><p>See an idea become a site, tool, or visual.</p></span><img class="category-card-mark" src="/azivor-logo.png" alt="" aria-hidden="true" width="512" height="408" loading="lazy"></a>
  <a class="category-card category-card--editorial" href="/explore/#workflows"><span class="category-card-copy"><h3>Workflows</h3><p>See how scattered steps become one useful way of working.</p></span></a>
  <a class="category-card category-card--image" href="/builds/#earth-descent"><span class="category-card-copy"><h3>Earth descent</h3><p>A real Azivor scene, with the decisions and limits behind it.</p></span></a>
  <a class="category-card category-card--compact" href="/explore/#new-capabilities"><span class="category-card-copy"><h3>New capabilities</h3><p>Find out what changes in practice when the tools change.</p></span></a>
</div><p class="ui-body">Four treatments for different content: a featured category, an editorial category, a real project, and a compact route. Each card is one link with a clear title and a short description.</p>`})}
${Section({id:'information-layout',title:'Information, with a reading path.',children:`<div class="information-gradient-demo" aria-hidden="true"></div><p class="ui-body">Interior hero transition: an eased OKLab blend with subtle grain and matching blue/cloud endpoints.</p><div class="footer-gradient-demo" aria-hidden="true"><strong>azivor.</strong><span>© 2026 Azivor</span></div><p class="ui-body">Footer: a smooth white-to-deep-blue gradient with light text.</p><p class="ui-body">Section titles orient the reader; project features, ordered processes, prose, and limitations have different roles. Interior headings remain Geist.</p><div class="editorial-split"><div class="section-intro"><p class="eyebrow">Build</p><h2>Inspect the work.</h2><p>A brief introduction stays separate from the detail.</p></div><div class="section-body">${BuildFeature()}</div></div><div class="editorial-split"><div class="section-intro"><p class="eyebrow">Process</p><h2>A clear sequence.</h2></div><div class="section-body">${Steps([['Make an attempt','<p>Start with your own judgment.</p>'],['Check the result','<p>Inspect what changed and explain why.</p>']], 'Example process')}<aside class="editorial-note"><h3>A visible limitation</h3><p>Notes clarify scope without hiding important context.</p></aside></div></div>`})}
${Section({id:'glass-nav',title:'Scroll navigation material',children:`<div class="catalog-glass-stage"><div class="glass-pill catalog-glass-demo"><span class="glass-pill__shine" aria-hidden="true"></span><span class="floating-nav__links"><span>Home</span><span>Explore</span><span>Builds</span><span>About</span></span></div></div><p class="ui-body">The 356 × 52 glass material uses the same centered link spacing as the top header. It appears near the end of the desktop Earth descent, or forms around the existing links on inner pages after scrolling. Its current-page capsule briefly slides to a clicked route before navigation. Mobile keeps the full-screen menu without a glass pill.</p>`})}
${Section({id:'forms',title:'Form demonstrations — no data is submitted or saved.',children:`<div class="ui-grid">${Card({variant:'solid',children:Field({id:'demo-name',label:'Project name',placeholder:'A new idea',help:'Demo only. Nothing is saved.'})})}${Card({variant:'solid',children:Field({id:'demo-error',label:'Email',type:'email',value:'incomplete',error:'Enter a complete email address.'})})}${Card({variant:'solid',children:Field({id:'demo-disabled',label:'Unavailable field',disabled:true,value:'Read-only example'})})}</div><pre tabindex="0"><code>${escapeHTML("Field({ id: 'email', label: 'Email', type: 'email', required: true })")}</code></pre><p class="ui-body">Fields include real labels, native validation, helper text, error associations, and disabled states. IDs must be unique on each page. Connect data handling when a real form is added.</p>`})}
${Section({id:'patterns',title:'Pieces that work together.',children:example('Brand and badge',Brand()+Badge({label:'In progress'}),"Brand({ href: '/' }) + Badge({ label: 'In progress' })")+Disclosure({title:'What is included?',children:'<p>Logo, brand links, navigation, button variants, glass cards, badges, fields, disclosures, sections, and responsive layout utilities.</p>'})+Disclosure({title:'How do I add a section?',children:'<p>Compose a Section with Cards and Buttons in a page module, then run the build. Use ui-stack, ui-cluster, and ui-grid for spacing and layout.</p>'})})}
${Section({id:'usage',title:'One system. More possibilities.',children:`<p class="ui-body">Author pages in src/pages. Import components from src/ui/components.mjs. Typography and theme values live in src/styles/tokens.css; the homepage hero alone uses EB Garamond. Other headings, text, and controls use Geist.</p><pre tabindex="0"><code>${escapeHTML("import { Section, Card, Button } from '../ui/components.mjs';\n\nSection({\n  id: 'next',\n  title: 'Your next idea',\n  children: Card({\n    variant: 'solid',\n    children: Button({ label: 'Explore', href: '/explore/' })\n  })\n});")}</code></pre><p class="ui-body">Run npm run build to generate the site; npm test checks the component contracts. No framework or package installation is required. HTML children are trusted author content; escape external text before embedding it.</p>`})}
</main><script src="/script.js" defer></script><footer class="ui-container catalog-footer">Azivor · Component library <a href="/">Back to the site</a></footer></body></html>`;}
